dist: bionic
sudo: required
services:
    - docker
language: c++
before_install:
    - sudo apt-get -y install python3-pip qemu-user-static
script:
    - "./build.sh"
cache: ccache
after_success: ccache --show-stats
