#!/bin/bash

set -e # exit on error
set -x # echo commands

# setup environment
source ./env.sh

# check if the last build finished the multistrap and configure stage
if [ -d ${ROOTFS}/etc/multistrap-success ]; then
    echo "Using cached rootfs"
else
    if [ -d ${ROOTFS} ]; then
        echo "Removing cached rootfs"
        rm -rf ${ROOTFS}
    fi
fi

# add machinekit keys to trusted keys dir
mkdir -p ${ROOTFS}/etc/apt/trusted.gpg.d
apt-key --keyring "${ROOTFS}/etc/apt/trusted.gpg.d/machinekit.gpg" adv --batch --keyserver hkp://keyserver.ubuntu.com:80 --recv 43DDF224

# multistrap
multistrap -f ${CONFIGDIR}/rootfs.conf -d ${ROOTFS}

# prepare to chroot
cp $(which qemu-arm-static) ${ROOTFS}/usr/bin
mkdir -p ${ROOTFS}/${PROJECTDIR}
mount -o bind /dev ${ROOTFS}/dev
mount -o bind /dev/pts ${ROOTFS}/dev/pts
mount -o bind /sys ${ROOTFS}/sys
mount -o bind ${PROJECTDIR} ${ROOTFS}/${PROJECTBASE}

# run configurescript
LC_ALL=C LANGUAGE=C LANG=C chroot ${ROOTFS} /bin/bash ${CONFIGDIR}/configscript.sh

# create a file indicating that multistrap and dpkg --configure successfully completed
touch ${ROOTFS}/etc/multistrap-success

# unbind chroot mounts
umount ${ROOTFS}/{sys,dev/pts,dev,${PROJECTBASE}}

# build Qt5
${QTDIR}/qtbuild.sh

# check for pyparted
if [ python3 -c "import parted" ]; then
    echo "Found pyparted"
else
    pip3 install -r pyparted
fi

# create and partition disk image
${UTILSDIR}/diskimage.py ${WORKDIR}/multistrap

# populate disk image

# install additional files under /etc

# archive the rootfs and upload to github