#!/bin/bash

set -e # exit on error
set -x # echo commands

# setup environment
source ./env.sh

# add machinekit keys to trusted keys dir
mkdir -p ${ROOTFS}/etc/apt/trusted.gpg.d
apt-key --keyring "${ROOTFS}/etc/apt/trusted.gpg.d/machinekit.gpg" adv --batch --keyserver hkp://keyserver.ubuntu.com:80 --recv 43DDF224

# multistrap
multistrap -f ${CONFIGDIR}/rootfs.conf -d ${ROOTFS}

# prepare to chroot
cp $(which qemu-arm-static) ${ROOTFS}/usr/bin
mkdir -p ${ROOTFS}/${PROJECTDIR}
mount -o bind /dev ${ROOTFS}/dev
mount -o bind /dev/pts ${ROOTFS}/dev/pts
mount -o bind /sys ${ROOTFS}/sys
mount -o bind ${PROJECTDIR} ${ROOTFS}/${PROJECTBASE}

# run configurescript
LC_ALL=C LANGUAGE=C LANG=C chroot ${ROOTFS} /bin/bash ${CONFIGDIR}/configscript.sh

# unbind chroot mounts
umount ${ROOTFS}/{sys,dev/pts,dev,${PROJECTBASE}}

# build Qt5
${QTDIR}/qtbuild.sh

# check for pyparted
if [ python3 -c "import parted" ]; then
    echo "Found pyparted"
else
    pip3 install pyparted
fi

# create and partition disk image
diskimage.py ${ROOTFS}

# populate disk image

# install additional files under /etc

# tar rootfs
tar cJf ${WORKDIR}/rootfs.tar.xz ${ROOTFS}
chmod a+rwx ${WORKDIR}/rootfs.tar.xz

# archive the rootfs and upload to github
